# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: deps:php:shared/libraries/PHPMailer

services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    # environment

    # - checkout
    # - run:
    #     name: SSH Configuration
    #     command: |
    #       sudo apt install sshpass
    #       ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
    # - run:
    #     name: Stash files to prepare for pull
    #     command: |
    #       sshpass -p $SSH_PASS ssh $SSH_USER@$SSH_HOST "git stash --quiet && git stash clear && exit"
    # - run:
    #     name: SSH Dreamhost Web deploy
    #     command: |
    #       sshpass -p $SSH_PASS ssh $SSH_USER@$SSH_HOST "git pull origin master && exit"
    # - run:
    #     name: SHH Dreamhost CMS deploy
    #     command: |
    #       sshpass -p $SSH_PASS ssh $SSH_USER@$SSH_HOST "yarn install && yarn build && npx pm2 startOrReload ecosystem.config.js --env production && npx pm2 save && exit"
